# Generated by Django 5.2.1 on 2025-06-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ETF",
            fields=[
                (
                    "ticker",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "underlying_asset",
                    models.CharField(help_text="e.g., TSLA, NVDA, QQQ", max_length=20),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[("Bullish", "Bullish"), ("Bearish", "Bearish")],
                        max_length=20,
                    ),
                ),
                (
                    "dividend_frequency",
                    models.CharField(
                        choices=[("Weekly", "Weekly"), ("Monthly", "Monthly")],
                        max_length=10,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "annual_yield_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "ETF",
                "verbose_name_plural": "ETFs",
                "ordering": ["ticker"],
            },
        ),
    ]
