# Generated by Django 5.2.1 on 2025-06-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="etf",
            name="next_ex_dividend_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="etf",
            name="price_vs_lower_median_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="etf",
            name="underlying_percent_from_6m_high",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="etf",
            name="underlying_percent_to_target",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="etf",
            name="underlying_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="etf",
            name="underlying_target_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
