# Generated by Django 5.2.1 on 2025-06-13 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0002_etf_next_ex_dividend_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExDividendRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ex_date", models.DateField()),
                (
                    "etf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ex_dividends",
                        to="screener.etf",
                    ),
                ),
            ],
            options={
                "ordering": ["-ex_date"],
            },
        ),
    ]
