# Generated by Django 5.2.1 on 2025-06-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0003_exdividendrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etf",
            name="dividend_frequency",
        ),
        migrations.AddField(
            model_name="etf",
            name="description",
            field=models.CharField(
                choices=[
                    (
                        "Synthetic Covered Call (Call-Write)",
                        "Synthetic Covered Call (Call-Write)",
                    ),
                    ("Covered Call (Call-Write)", "Covered Call (Call-Write)"),
                    ("Leverage", "Leverage"),
                    ("Put-Write", "Put-Write"),
                    ("Put-Buy/Write", "Put-Buy/Write"),
                    ("Credit Call Spreads", "Credit Call Spreads"),
                    (
                        "Synthetic Covered Put (Put-Write)",
                        "Synthetic Covered Put (Put-Write)",
                    ),
                ],
                default="Synthetic Covered Call (Call-Write)",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="etf",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("Bullish", "Bullish"),
                    ("Bullish Leveraged", "Bullish Leveraged"),
                    ("Bearish", "Bearish"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="etf",
            index=models.Index(fields=["ticker"], name="screener_et_ticker_816dcd_idx"),
        ),
        migrations.AddIndex(
            model_name="etf",
            index=models.Index(
                fields=["underlying_asset"], name="screener_et_underly_ecfdf3_idx"
            ),
        ),
    ]
