# Generated by Django 5.2.1 on 2025-06-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0004_remove_etf_dividend_frequency_etf_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="etf",
            name="fund_issuer",
            field=models.CharField(default="YieldMax", max_length=100),
        ),
    ]
