# Generated by Django 5.2.1 on 2025-06-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0005_etf_fund_issuer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etf",
            name="fund_issuer",
            field=models.CharField(
                choices=[
                    ("YieldMax", "YieldMax"),
                    ("Roundhill", "Roundhill"),
                    ("GraniteShares", "GraniteShares"),
                    ("RexShares", "RexShares"),
                    ("Kurv", "Kurv"),
                    ("Defiance", "Defiance"),
                ],
                default="YieldMax",
                max_length=50,
            ),
        ),
    ]
