# Generated by Django 5.2.1 on 2025-06-05 18:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_lot_options_alter_lot_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_margin_used",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="marginal_tax_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0.3700"),
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="monthly_goal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("12000.00"),
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="nav_goal",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="nlv_goal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("250000.00"),
                max_digits=12,
                null=True,
            ),
        ),
    ]
