# Generated by Django 5.2.1 on 2025-06-05 19:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_userprofile_current_margin_used_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="margin_interest_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0.0700"),
                max_digits=5,
                null=True,
            ),
        ),
    ]
